import { expect, test } from "@playwright/test";
test("admin can create edit and delete user", async ({ page }) => {
  const firstName = "John";
  const updatedFirstName = "Mike";
  const email = `user${Date.now()}@test.com`;
  await page.goto("/auth/signin");
  await page.locator('input[name="email"]').fill("123@mail.com");
  await page.locator('input[name="password"]').fill("123456");
  await page.locator('button[type="submit"]').click();
  await page.waitForURL(/users/);
  await expect(page).toHaveURL(/users/);
  await page.getByTestId("add-new-btn").click();
  const createDialog = page.getByRole("dialog");
  await expect(createDialog).toBeVisible();
  await createDialog.locator('input[name="email"]').fill(email);
  await createDialog.locator('input[name="password"]').fill("123456");
  await createDialog.locator('input[name="firstName"]').fill(firstName);
  await createDialog.locator('input[name="lastName"]').fill("Doe");
  await createDialog.getByTestId("department-select").click();
  await page.getByRole("option", { name: "React", exact: true }).click();
  await createDialog.getByTestId("position-select").click();
  await page
    .getByRole("option", { name: "Software Engineer", exact: true })
    .click();
  await createDialog.getByTestId("confirm-btn").click();
  await expect(page.getByText(firstName)).toBeVisible();
  await page.getByTestId("search-input").fill(firstName);
  await expect(page.locator("tbody tr")).toHaveCount(1);
  const row = page.locator("tbody tr").first();
  await row.locator('button[data-part="trigger"]').click();
  const popover = page.locator('[data-part="content"][role="dialog"]');
  await expect(popover.getByTestId("menu-link")).toBeVisible();
  await expect(popover.getByTestId("edit-btn")).toBeVisible();
  await expect(popover.getByTestId("delete-btn")).toBeVisible();
  await popover.getByTestId("edit-btn").click();
  const editDialog = page.getByRole("dialog");
  await expect(editDialog).toBeVisible();
  const firstNameInput = editDialog.locator('input[name="firstName"]');
  await firstNameInput.clear();
  await firstNameInput.fill(updatedFirstName);
  const lastNameInput = editDialog.locator('input[name="lastName"]');
  await lastNameInput.clear();
  await lastNameInput.fill("Smith");
  await editDialog.getByTestId("confirm-btn").click();
  await page.getByTestId("search-input").clear();
  await page.getByTestId("search-input").fill(updatedFirstName);
  await expect(page.locator("tbody tr")).toHaveCount(1);
  await expect(page.getByText(updatedFirstName)).toBeVisible();
  const updatedRow = page.locator("tbody tr").first();
  await updatedRow.locator('button[data-part="trigger"]').click();
  const updatedPopover = page.locator('[data-part="content"][role="dialog"]');
  await updatedPopover.getByTestId("delete-btn").click();
  await page.getByTestId("search-input").clear();
  await page.getByTestId("search-input").fill(updatedFirstName);
  await expect(page.locator("tbody tr")).toHaveCount(0);
});
